language: node_js
services:
  - docker

stages:
  - build
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - name: Build docker image
      stage: build
      env:
        - DOCKER_USERNAME=lbassin
        - DOCKER_PROJET=k8s-training
        - DOCKER_TAG=$TRAVIS_COMMIT
        - BUILD_NAME=$DOCKER_USERNAME/$DOCKER_PROJECT:$DOCKER_TAG
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t BUILD_NAME .
        - docker push BUILD_NAME

    - name: Unit tests
      stage: test
      script:
        - sh -c "return 0;"
    - name: Functional tests
      stage: test
      script:
        - sh -c "return 0;"

    - name: Deploy to k8s
      stage: deploy
      script:
        - sh -c "return 0;"
